### ISSUE TITLE
you accidentally made __init__ anti-linter

### ISSUE THREAD

**Issue by kelvinwop** [skvark/opencv-python#131]
### Expected behaviour

be detected by linter

### Actual behaviour

not detected by linter

### Steps to reproduce

- install opencv-python
- use vscode >extension microsoft python linter
- try to use cv2 methods
- # RED SQUIGGLY LINES

## I blame:
\cv2\\\_\_init\_\_.py:
>import importlib
>
>from .cv2 import *
>from .data import *
>
>\# wildcard import above does not import "private" variables like \_\_version\_\_
>\# this makes them available
>globals().update(importlib.import_module('cv2.cv2').\_\_dict\_\_)

**Comment by skvark** [comment]
This seems to be a pylint issue. Add cv2 to the pylint extension package whitelist as suggested by this answer at Stack Overflow: https://stackoverflow.com/a/51916065/5795428

The wildcard import code in the ``__init__`` file is perfectly valid Python. There's nothing "anti-linter" in the file. The last line is a bit hacky, but as the comment implies, it's needed to expose members which are ignored by the wildcard import. 

I believe that the actual problem is related to the fact that the cv2 is binary extension module. For example Numpy behaves excatly the same way with pylint / vscode: https://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members

**Comment by kelvinwop** [comment]
Strange. Seems to work with numpy lol.

Will add this link to the vscode issue
