### ISSUE TITLE
cv2.copyMakeBorder segmentation fault

### ISSUE THREAD

**Issue by snk4tr** [skvark/opencv-python#143]
### Expected behavior
ValueError: passed image has wrong shape. Expected to have 3 dimensions, has 4.

### Actual behavior
31807 segmentation fault (core dumped)

(neither stack trace nor place of occurred error provided which is very inconvenient to debug)

### Steps to reproduce

- example code
```python
import cv2
import numpy as np

# Example image. 
# May also be an image loaded with opencv-python with np.expand_dims(img, 0) or similar.
img = np.zeros((1, 256, 256, 3), dtype=np.uint8)
cv2.copyMakeBorder(img, 1, 1, 1, 1, cv2.BORDER_CONSTANT, value=[0, 0, 0])
```
- operating system:
Ubuntu 16.04 (64-bit) in Docker 18.09.0.

- architecture (e.g. x86):
Intel® Core™ i5-7500 CPU @ 3.40GHz × 4.

- opencv-python version:
opencv-python==3.4.3.18

**Comment by native-api** [comment]
[You can examine the core dump with `gdb`.](https://stackoverflow.com/questions/8305866/how-to-analyze-a-programs-core-dump-file-with-gdb) There, you should see the C-level stack. There can not be a Python stack because on a segmentation fault, the OS terminates the process, Python has no chance to do anything ([nor is it _safe_ to try to do anything tbh](https://stackoverflow.com/questions/2663456/how-to-write-a-signal-handler-to-catch-sigsegv)).

If you're going to run in under debugger after this though, note that [you may need to adjust Docker settings for breakpoints to work.](https://stackoverflow.com/questions/34856092/gdb-does-not-hit-any-breakpoints-when-i-run-it-from-inside-docker-container)

**Comment by snk4tr** [comment]
Thank you for your fast response, @native-api! 
Do you confirm it as a bug and if so is it a bug on python or C level? I suppose in case if C code can't work with 4-D tensors there should be a check in python to prevent such cases.

**Comment by skvark** [comment]
You should open an issue to the upstream repository at https://github.com/opencv/opencv/issues. All code related to OpenCV is implemented in C++. Only Python code in this repository is the ``__init__.py`` wrapper which imports the statically built OpenCV binary. It's very likely that this issue cannot be fixed here unless the issue is somehow related to the build process.

**Comment by snk4tr** [comment]
@skvark ok, I will. Thanks, closing then.
