### ISSUE TITLE
Add GUI support (Qt)

### ISSUE THREAD

**Issue by esc** [skvark/opencv-python#17]
Hi, I am having trouble with the library, I installed it and tried to use it on:

https://github.com/gliese581gg/YOLO_tensorflow

But the error I get when trying to run it is:

```
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /io/opencv/modules/highgui/src/window.cpp, line 545
Traceback (most recent call last):
  File "YOLO_small_tf.py", line 250, in <module>
    main(sys.argv)
  File "YOLO_small_tf.py", line 245, in main
    yolo = YOLO_TF(argvs)
  File "YOLO_small_tf.py", line 30, in __init__
    if self.fromfile is not None: self.detect_from_file(self.fromfile)
  File "YOLO_small_tf.py", line 137, in detect_from_file
    self.detect_from_cvmat(img)
  File "YOLO_small_tf.py", line 129, in detect_from_cvmat
    self.show_results(img,self.result)
  File "YOLO_small_tf.py", line 225, in show_results
    cv2.imshow('YOLO_small detection',img_cp)
cv2.error: /io/opencv/modules/highgui/src/window.cpp:545: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage
```

**Comment by skvark** [comment]
On which OS you get this error? The error appears because OpenCV provided by this repo has not been built with GTK support (it can be enabled, but it requires work at least on Linux due to the Cent OS 5 containers).

**Comment by esc** [comment]
Ubuntu 16.04

**Comment by cachitas** [comment]
Just to be more specific, I've encountered this problem when using `cv2.imshow()` and `cv2.waitKey()`.

**Comment by skvark** [comment]
The error says: "Rebuild the library with Windows, GTK+ 2.x or Carbon support.". OpenCV needs to be compiled with GTK support (`WITH_GTK=ON`). Currently I'm too busy to add support for this, but I'll have a look at the issue as soon as I have more spare time. Same thing with ffmpeg on Linux. Testing the builds is very time consuming stuff.

**Comment by esc** [comment]
it would be very convenient for us to get this working, is there anything I can do to help?

**Comment by skvark** [comment]
You can fork the repo and try to tune the build scripts. First you should try to install GTK+ 2.x to the CentOS container (`yum install gtk2` might be enough) and after that make OpenCV build scripts to find it. After that write some test scripts which utilize for example cv2.imshow() to confirm that the build was ok.

**Comment by fmntf** [comment]
Hi. Any progress on this?

**Comment by skvark** [comment]
I haven't had time to look at this.

**Comment by Greendogo** [comment]
This still needs to be fixed badly.  Any progress on this critical issue?

OpenCV is rather useless for computer vision if you can't use it to efficiently display output.

**Comment by skvark** [comment]
I have an idea how this could be implemented. However, introducing a new dependency (GTK) without breaking the library import on every system is not an easy task. After all, there are hundreds of GNU/Linux distributions which don't necessarily have GTK binaries easily available (including the Cent OS 5 containers where the packages are built). Implementing this will take time and surely you know that I'm doing this for free on my limited free time. 

Additionally, I don't think that OpenCV is useless without GUI features. It was never meant to be a comprehensive GUI framework. It might be good for showing images for debugging purposes, but there are many better ways to draw the images on the screen if needed. Here are few suggestions:

- matplotlib
- PIL (pillow)
- scikit-image
- tkinter
- kivy

And you can always build OpenCV from sources.

**Comment by zixia** [comment]
I suggest we consider to publish an OpenCV python module with Gtk/Qt support. 

Today I spent serval hours on building OpenCV from scratch in order to use 'cv2.imshow()`.

If add new dependency is a problem, how about publishing a new module with Gtk/Qt support, like **opencv-python-gtk** and **opencv-python-qt** ?

**Comment by Greendogo** [comment]
I second having two additional modules for gtk and qt.  I found that qt was easier to get working than gtk, but I'm on Ubuntu, so it wasn't super difficult.  I don't think Cent OS 5 has either GTK+ 2.x (which is what imshow requires) or Qt by default, so that might not work for skvark.

@skvark - I've tried using those libraries for my purposes, however sometimes that requires rewriting large portions of code that already should work with OpenCV to instead work with another image display library.  Another problem is performance, OpenCV displays images fast, which is definitely important for demo-ing a live feed from a tracking network (for example).

**Comment by skvark** [comment]
I'll try to compile the packages with GTK to avoid separate packages. I hope that auditwheel / delocate can handle the dependencies automatically and embed them to the wheels. For this to work I have to fork the manylinux CentOS 5 containers and build GTK support to them manually since the default GTK provided in the EL5 repos is too old (2.10 and OpenCV needs at least 2.18). This should be easy with Docker. For macOS I'll have to go with homebrew and hope that the build times don't get too long.

**Comment by skvark** [comment]
I have been testing different build setups during the last two weeks. Building newer version of GTK was too complicated so instead of GTK I built Qt 4.8.7 manually on the manylinux containers. These new customized containers seem to be working fine and the Linux wheels should have GUI support in the upcoming releases.

I'll see if I can enable Qt on macOS builds too.

**Comment by skvark** [comment]
The release builds for [3.3.0.10](https://github.com/skvark/opencv-python/releases/tag/10) are now in progress and the GUI supported wheels should be available to install during the next couple of hours. Please report if you have any issues with them.

**Comment by owend** [comment]
Hi, I did run into an issue with headless (docker) versions of ubuntu. #44  I think anyone running opencv-python in a cloud environment without X11 is going to have the same issue.

**Comment by YerongLi** [comment]
Get exact a same error, any idea on the a best way to fix this?

**Comment by zitgost** [comment]
Maybe some of us are confused as to what to do rather than fix this. If OpenCV does not work in our environments, could you explain what environments it does work in? Should I just get a windows PC and visual studio and scrap XCode altogether?

**Comment by zitgost** [comment]
Should I be using a different IDE to avoid this error? I'm currently using Xcode 9.

**Comment by skvark** [comment]
Could you elabolarate a bit more what it is excatly you're trying to do? This issue has been closed over a year ago. All recent ``opencv-python`` (given that you installed ``opencv-python`` as described in the README) releases have GUI support. The IDE you use is not related to this library in any way.

**Comment by KBor-DSIC** [comment]
pip install opencv-python fixed this issue for me

**Comment by be42day** [comment]
It's because of 'opencv-python-headless'. Uninstall it!
`pip uninstall opencv-python-headless`

**Comment by arafatx** [comment]
This one work for me on facefusion installation

```
pip uninstall opencv-python-headless -y 

pip install opencv-python --upgrade
```

**Comment by LinneLee** [comment]
uninstall opencv-python-headless doesn't work in my linux server
