### ISSUE TITLE
Build custom wheels from specific OpenCV commits

### ISSUE THREAD

**Issue by iindovina** [skvark/opencv-python#173]
Hi,
Thanks for all the effort you have put in this project, it is really amazing. 
I wanted to build custom Linux wheels for a specifc development branch of OpenCV, but I can't seem to find instructions or steps on how to build or run things in your repository. I would probably be interested in using the dockerfiles you provide so I can build different versions, but I am not too familiar with it.
Could you please give me a hint on how to do it?

Thanks

**Comment by skvark** [comment]
The ``setup.py`` has not been designed to run locally (see https://github.com/skvark/opencv-python/issues/43), but local builds should be doable if you run similar steps as in the Docker containers (https://quay.io/repository/skvark/manylinux1_x86_64). Check ``.travis.yml`` (before_install and install).

If you do not need manylinux1 (universally GNU/Linux compatible) wheels, then you can just try to to run ``setup.py bdist_wheel`` on your Linux machine. In this case you will have to modify the ``setup.py`` file a bit since currently it's assumed that the build is run in the custom containers.

To use a specific commit or branch, just checkout the desired branch or commit in the ``opencv`` and ``opencv_contrib`` submodules.
