### ISSUE TITLE
headless package requires "libglib2.0-0" 

### ISSUE THREAD

**Issue by luzlab** [skvark/opencv-python#203]
### Expected behaviour

Expected to be able to use "opencv-python-contrib-headless" inside a docker container based on the "python-2.7-slim" image.

### Actual behaviour

There's an exception thrown at `import cv2` with a message about not being able to find libglib2.0-0. 

### FIx

Adding `RUN apt-get update && apt-get install libglib2.0-0` to the Dockerfile fixes the problem.

I'm not sure this qualifies as a bug, but I thought it might be helpful in case someone else runs into this problem as well.

**Comment by skvark** [comment]
Libglib is excluded from the wheel bundles so you have to install it yourself. This is dictated by [PEP 513](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy). 

Glib is a low level system library and it's required by OpenCV.

**Comment by fzqneo** [comment]
Is there a list of Linux packages to install before one can install from PyPI and use it? I encountered the same problem when trying to use it in Docker.

Thanks for creating this project. It has been very useful.

**Comment by skvark** [comment]
No, there's no list except the PEP 513 list here https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy. The actual package names usually vary between distros so it's impossible to create a universal list of install commands / actual package names. I believe that for example Glib is often excluded in Docker images to make the image smaller. For example the X Windows System is a dependency in non-headless packages and due to that those packages require libX11.so.6, libXext.so.6, libXrender.so.1 etc. 

All other dependencies, such as Qt and FFmpeg, ship with the PyPI packages.

You can install opencv-python from PyPI before installing any of the the dependencies. Linux will tell which dependencies are missing during import / dynamic linking (during ``import cv2``). You can also check missing dependencies for example with ``ldd`` beforehand.

**Comment by x-yuri** [comment]
`libglib2.0-0` was needed for `opencv-python-headless >= 4.0.0.21, < 4.3.0.38`.

P.S. Care to add tags to commits to see which commit corresponds to which version?.. Couldn't find versions in the source code as well.

**Comment by skvark** [comment]
> `libglib2.0-0` was needed for `opencv-python-headless >= 4.0.0.21, < 4.3.0.38`.
> 
> P.S. Care to add tags to commits to see which commit corresponds to which version?.. Couldn't find versions in the source code as well.

Could you clarify what you mean? There is a tag for each version. For example, for 4.3.0.38 the tag is 38. Check out the README for more info about versioning.

**Comment by x-yuri** [comment]
Oh, I see, I saw the tags, but it didn't occur that those are version numbers. And I didn't notice that the fourth number is independent from the first three. As such not particularly expected, but maybe okay.
