### ISSUE TITLE
opencv-contrib-python 3.4.4 did not install opencv/data/ -  (e.g. cascade detectors)

### ISSUE THREAD

**Issue by slowrunner** [skvark/opencv-python#206]
For some reason my cv2.data.haarcascades variable points to '/usr/local/lib/python3.5/dist-packages/cv2/data/', but that location only has __init__.py and __pycache__ folder (which only has __init__.cpython-35.pyc in it) but there are no example cascade detectors under opencv/data/.  There are quite a few python opencv face-detection tutorials on the net that expect the haarcascade and lbpcascade detectors come with opencv-contrib-python. 

This is how I installed OpenCV on my RaspberryPi Raspbian(forRobots) Stretch version:

```
sudo apt-get install libhdf5-dev libhdf5-serial-dev libhdf5-100
sudo apt-get install libqtgui4 libqtwebkit4 libqt4-test python3-pyqt5
sudo apt-get install libatlas-base-dev
sudo apt-get install libjasper-dev
wget https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py
sudo pip install opencv-contrib-python
```

# Q: I managed to get opencv/data/, but could it come with opencv-contrib-python?  Or can there be an opencv-data pip package?

ps. this is what I did to get the data folder:

```
cd ~/Carl/Examples/OpenCV/
wget https://github.com/opencv/opencv/archive/3.4.4.zip
unzip *.zip
```

Data is in ~/Carl/Examples/OpenCV/opencv-3.4.4/data

**Comment by skvark** [comment]
The packages which are generated by this repository ship with the data (I confirmed this by downloading and unzipping a wheel while directly from PyPI: https://pypi.org/project/opencv-contrib-python/#files).

I see you are using Raspberry Pi. You should open an issue to https://github.com/bennuttall/piwheels since the Raspberry Pi wheels are generated there.
