### ISSUE TITLE
Could not find encoder for codec id 27: Encoder not found

### ISSUE THREAD

**Issue by acodercat** [skvark/opencv-python#207]
OpenCV: FFMPEG: tag 0x34363258/'X264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
Could not find encoder for codec id 27: Encoder not found

**Comment by skvark** [comment]
H264 encoding is not supported because it falls under GPL license. See: https://github.com/skvark/opencv-python/issues/100

You must build OpenCV yourself and link it with system FFmpeg.

About licensing:

If I ship GPL'ed components with ``opencv-python`` I would have to re-license the whole package under GPL license and any package using opencv-python, respectively, would have to be licensed under GPL. This would also mean that this package or any package which uses opencv-python could not be used for commercial purposes / proprietary applications unless you are willing to publish your software source code.

**Comment by leimao** [comment]
This helps. Thank you.

**Comment by sunnie-star** [comment]
> H264 encoding is not supported because it falls under GPL license. See: #100
> 
> You must build OpenCV yourself and link it with system FFmpeg.
> 
> About licensing:
> 
> If I ship GPL'ed components with `opencv-python` I would have to re-license the whole package under GPL license and any package using opencv-python, respectively, would have to be licensed under GPL. This would also mean that this package or any package which uses opencv-python could not be used for commercial purposes / proprietary applications unless you are willing to publish your software source code.

But  how can I do?

**Comment by skvark** [comment]
> > H264 encoding is not supported because it falls under GPL license. See: #100
> > You must build OpenCV yourself and link it with system FFmpeg.
> > About licensing:
> > If I ship GPL'ed components with `opencv-python` I would have to re-license the whole package under GPL license and any package using opencv-python, respectively, would have to be licensed under GPL. This would also mean that this package or any package which uses opencv-python could not be used for commercial purposes / proprietary applications unless you are willing to publish your software source code.
> 
> But how can I do?

Follow the manual build instructions in the readme: https://github.com/opencv/opencv-python#manual-builds

**Comment by sunnie-star** [comment]
Thank&nbsp; you! I will try.



---Original---
From: "Olli-Pekka ***@***.***&gt;
Date: Wed, Mar 31, 2021 15:56 PM
To: ***@***.***&gt;;
Cc: "Lin ***@***.******@***.***&gt;;
Subject: Re: [opencv/opencv-python] Could not find encoder for codec id 27: Encoder not found (#207)




   
H264 encoding is not supported because it falls under GPL license. See: #100
 You must build OpenCV yourself and link it with system FFmpeg.
 About licensing:
 If I ship GPL'ed components with opencv-python I would have to re-license the whole package under GPL license and any package using opencv-python, respectively, would have to be licensed under GPL. This would also mean that this package or any package which uses opencv-python could not be used for commercial purposes / proprietary applications unless you are willing to publish your software source code.
  
But how can I do?
  
Follow the manual build instructions in the readme: https://github.com/opencv/opencv-python#manual-builds

**Comment by rajkundu** [comment]
If you are using conda, uninstalling OpenCV through `pip` and instead using `conda install -c conda-forge opencv` worked for me! I can run `cv2.VideoWriter('out.mp4', cv2.VideoWriter_fourcc(*'avc1'), FPS, (WIDTH, HEIGHT))` without issues.

**Comment by relaxandcodezjmo** [comment]
> If you are using conda, uninstalling OpenCV through `pip` and instead using `conda install -c conda-forge opencv` worked for me! I can run `cv2.VideoWriter('out.mp4', cv2.VideoWriter_fourcc(*'avc1'), FPS, (WIDTH, HEIGHT))` without issues.

Thank you so much you saved my day! This IS the SOLUTION!
