### ISSUE TITLE
Feature Request: Include inference engine

### ISSUE THREAD

**Issue by ohlr** [skvark/opencv-python#214]
To be able to use: `cv2.dnn.readNetFromModelOptimizer` openCV must be build with the [Inference Engine](https://github.com/opencv/dldt). Are there any plans to add this feature?

There already exists a repo that does it [opencv-python-inference-engine](https://github.com/banderlog/opencv-python-inference-engine) however, it only supports Ubuntu 18.04 and above

**Comment by native-api** [comment]
This looks like a heavy dependency (comparing https://pypi.org/project/opencv-python-inference-engine/#files and https://pypi.org/project/opencv-python-headless/#files suggests +8MB to archive size (probably more since the `engine` build has a few other modules disabled) so expect x2-3 to the file size).

How big is the niche for it? And how homogeneous -- https://docs.openvinotoolkit.org/latest/_docs_IE_DG_inference_engine_intro.html suggests that the Engine lib has lots of optional modules of its own? If the required configuration would end up too niche, a custom build for your specific use case would probably be a better option.

**Comment by skvark** [comment]
I think we could make a modification to the ``setup.py`` so that if you run ``python setup.py install`` it builds OpenCV in some kind of default configuration depending on the system where it is run. Users could then build a custom version by appending Cmake flags to the ``python setup.py install`` command. We could also release ``sdist`` to PyPI. For CI purposes the ``setup.py`` file should accept some special flags to run the builds in special configurations specific to this repo. This is just an idea, but it would make for example local builds easier.

**Comment by native-api** [comment]
> Users could then build a custom version by appending Cmake flags to the `python setup.py install` command.

That's easy: https://github.com/skvark/opencv-python/pull/235
