### ISSUE TITLE
openCV-python 

### ISSUE THREAD

**Issue by deventank7** [skvark/opencv-python#233]
Hello,
I am using python3.7.3 on raspberry pi with latest raspbian OS.

I was running simple opencv code and I got the error- No module cv2
I used the command- sudo apt-get install python-opencv
It got successfully installed, but after  running the below command
sudo pip3 install opencv-python

I am getting the following error-

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python
 Could not find a version that satisfies the requirement opencv-python (from versions: )

Please help me with this issue.

Is is so that python3.7 does not support opencv2 ???

**Comment by abiro** [comment]
Installing `opencv-python` with `python==3.7` and `pip==19.1.1` doesn't work.

**Comment by deventank7** [comment]
https://www.alatortsev.com/2018/11/21/installing-opencv-4-0-on-raspberry-pi-3-b/

After going through the above link. I followed the steps and now it's working.

**Comment by abiro** [comment]
@deventank7 the link provides a workaround by complying from source. The point of this package is to use prebuilt binaries, so I don’t think it’s a solution. Please reopen the issue as it is not solved!

**Comment by skvark** [comment]
This repository does not provide Raspberry Pi compatible wheels as stated in the README. This question pops up almost every week now so **please read the README file before you open an issue.** https://github.com/skvark/opencv-python#frequently-asked-questions

PiWheels is the project that provides Raspberry Pi compatible wheels. Please follow the issue at PiWheels: https://github.com/piwheels/packages/issues/28

**Comment by abiro** [comment]
Apologies, I had this same issue on x86 ubuntu, but it's resolved after installing the `build-essential` package.

**Comment by skvark** [comment]
For future reference:

``pip install opencv-python`` does not require ``build-essential``. It's required only if you are building OpenCV manually from sources. Note that if you wish to use ``opencv-python`` packages provided by this repository you should _never_ install OpenCV via ``sudo apt-get install python-opencv`` because it's a completely different package provided by your Linux distribution package manager and installing it next to these packages will break ``import cv2``.

So this is very wrong:

> I used the command- sudo apt-get install python-opencv
> It got successfully installed, but after running the below command
> sudo pip3 install opencv-python

This is also very clearly stated in the README in step 1. at https://github.com/skvark/opencv-python#installation-and-usage

Only thing you need to do is run ``pip install opencv-python`` if you are on Windows, macOS or on some x86 GNU/Linux distribution and make sure you have no other OpenCV installations present in your Python enviroment.
