### ISSUE TITLE
installation on Ubuntu ppc64le

### ISSUE THREAD

**Issue by Borda** [skvark/opencv-python#247]
## Expected behaviour

I want to install this package on Ubuntu ppc64le architecture but it constantly tells me that there is no available version... I have used docker image and compiled OpenCV from source, similar as it is [here](https://github.com/Borda/docker_python-opencv-ffmpeg/blob/master./Dockerfile_cuda#L59) which succeed but then installing `opencv-python` fails...

## Actual behaviour

```
Collecting pip
  Using cached https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.2.3

$ pip install opencv-python
Collecting opencv-python
  ERROR: Could not find a version that satisfies the requirement opencv-python (from versions: none)
ERROR: No matching distribution found for opencv-python
```

## Steps to reproduce

- docker source: https://hub.docker.com/r/nvidia/cuda-ppc64le
- operating system: `FROM nvidia/cuda-ppc64le:10.0-runtime-ubuntu18.04`
- architecture: ppc64le
- opencv-python version - last

**Comment by skvark** [comment]
There are no builds for your architecture. If you compile OpenCV manually (like you have done), then ``opencv-python`` is obsolete. This repository just provides an automatic toolchain for Python to compile OpenCV Python bindings and generates pre-built packages for some popular architectures and uploads them to PyPI (see https://pypi.org/project/opencv-python/#files, no ``ppc64le`` wheel there -> pip complains about missing distribution).

However, if you wish to have ``opencv-python`` wheel package for your architecture, then you must execute following commands:

``git clone https://github.com/skvark/opencv-python``
``cd opencv-python``
``python setup.py bdist_wheel`` (this will take 10+ minutes)
``cd dist``
``pip install generated_wheel_package.whl``

**Comment by Borda** [comment]
Well I have tried also following with the same failer...
`pip install https://github.com/skvark/opencv-python/archive/master.zip`
Which should do the build too, right?

**Comment by Borda** [comment]
Btw, having compiled openCV manually and installing `opencv-python` from `pip` uses my custom build or does it creates another copy (binaries/compilation)?

**Comment by skvark** [comment]
> Well I have tried also following with the same failer...
> pip install https://github.com/skvark/opencv-python/archive/master.zip
> Which should do the build too, right?

The ``setup.py`` `logic currently assumes that it's run inside a directory which is a Git repository (because ``setup.py`` clones opencv and opencv_contrib submodules) so that command will fail. I'll try to publish a source tarball in the next release which means that ``pip install opencv-python`` will fall back to manual build if a compatible pre-built wheel is not found from PyPI.

> Btw, having compiled openCV manually and installing opencv-python from pip uses my custom build or does it creates another copy (binaries/compilation)?

This repository has nothing to do with your custom build. In fact, the first step in the README says that you must remove other manually installed OpenCV python binding versions if you wish to use ``opencv-python``. ``opencv-python`` uses its own copy of OpenCV. 

You either use ``opencv-python`` OR you compile OpenCV manually and install it manually to your Python environment. You can't use both simultaneously because they are two different packages.
