### ISSUE TITLE
why isn't there a none-free package for windows?

### ISSUE THREAD

**Issue by Thenorthernsea** [skvark/opencv-python#283]
I see some linux versions but no windows thus wonder why.

**Comment by skvark** [comment]
This repository does not provide any non-free packages. It's illegal to distribute patented algorithms. Some guy has uploaded them to PyPI and I have nothing to do with those packages. I have sent an email to the guy to remove my name from those packages but since he hasn't answered I'll probably have to issue a takedown notice to PyPI concerning those packages.
