### ISSUE TITLE
SystemError when passing wrong type

### ISSUE THREAD

**Issue by nog642** [skvark/opencv-python#289]
`cv2.imwrite` (and maybe other functions too) seems to lack type checking, or not properly raise an exception when typechecking. I discovered this by accidentally switching the file name and the image arguments, which can't be too uncommon of a thing to do. The error message I got was unhelpful though, and debugging took much longer than it should have.

### Expected behaviour

```python
>>> img = cv2.imread('in.jpg')
>>> cv2.imwrite(img, 'out.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument 1 must be str, not numpy.ndarray
```

Or some other reasonable error message.

### Actual behaviour

```python
>>> img = cv2.imread('in.jpg')
>>> cv2.imwrite(img, 'out.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function imwrite> returned NULL without setting an error
```

### Steps to reproduce

I'm running this in a virtualenv with python version 3.6.9, with `numpy==1.18.1` and `opencv-python==4.1.2.30`.

**Comment by skvark** [comment]
Please report the issue to the OpenCV repository: https://github.com/opencv/opencv/issues

This repository contains only package build toolchain for Python. There is no OpenCV related code in this repository. The actual OpenCV code is C++ and type checks can be done only in there.

**Comment by nog642** [comment]
The Python wrapper has to be the one to raise Python exceptions, not the C++ OpenCV library.

This is concerning type checks _before_ attempting conversion from `PyObject *` to whatever the OpenCV functions take.

The `SystemError` here is because Python functions are not supposed to return `NULL` at the C level without setting an error. From what I understand, this repository generates Python wrappers for OpenCV, and that generated code is responsible for setting the Python error with one of the `PyErr_*` functions when there is an error.

Otherwise, the Python error messages can be unhelpful, as it was in this case.

**Comment by skvark** [comment]
The generators are in the OpenCV repository (see https://docs.opencv.org/master/da/d49/tutorial_py_bindings_basics.html and https://github.com/opencv/opencv/tree/master/modules/python). 

This repository, as explained in the README, provides just the surrounding Python tools to package the generated ouput to a valid precompiled Python package which can be easily installed via pip. This means that there are a bunch of CI scripts, environment setup tooling etc. which in the end trigger OpenCV CMake-based build. Build output (``cv2`` binary) is then copied to this thin wrapper package so that it can be installed (and imported) properly with standard Python tools such as ``pip``.

I'm not going to extend or augment the generated bindings here. If you need better error messages or you have other development ideas regarding the binding generators, please open an issue to the OpenCV repository.
