### ISSUE TITLE
Version 4.3.9.33 on PyPI

### ISSUE THREAD

**Issue by killzoner** [skvark/opencv-python#312]
Hello i'm wondering if there is any reason why 4.3.9.33 version is not on PyPI and 4.2.0.34 released the same day is ?

### Expected behaviour

Version 4.3.9.33 is available at PyPI following the links mentionned in release (https://pypi.org/project/opencv-python/, https://pypi.org/project/opencv-python/, etc.)

### Actual behaviour

Version 4.3.9.33 is not available

### Steps to reproduce

Go to https://pypi.org/project/opencv-python/

**Comment by skvark** [comment]
Sorry, there was a copy-paste typo in the releases page. The correct version is 3.4.9: https://pypi.org/project/opencv-python/3.4.9.33/

Note that it will not show up as a first entry in PyPi since 3.4.9 is the older branch of OpenCV and will be inserted as a "older" release to the releases list according to semantic versioning practices: https://pypi.org/project/opencv-python/#history

The release numbering follows OpenCV versioning (the last sequential number is just a tag which points to some commit in this repository): https://github.com/opencv/opencv/releases
