### ISSUE TITLE
provide a version table for older macos's ?

### ISSUE THREAD

**Issue by parmentelat** [skvark/opencv-python#338]
### Expected behaviour

```bash
pip install opencv-python
python -c 'import cv2'
```

### Actual behaviour

```bash
pip install opencv-python
python -c 'import cv2'
```

![image](https://user-images.githubusercontent.com/4519227/83856336-aa376700-a719-11ea-818e-e84a3d602a19.png)

### comments

[this SO article here](https://stackoverflow.com/questions/60254766/opencv-giving-an-error-whenever-import-cv2-is-used) suggests that an older version of opencv-python might work on this macos

if this SO article is right, without changing the code, it would maybe help to provide some data in the documentation for people to be able to select the right version for their actual OS version

**Comment by skvark** [comment]
4.2.0 and 3.4.9 updated the macOS environment in Travis to XCode 9.4. This is documented in the releases page: https://github.com/skvark/opencv-python/releases/tag/32 

The change effectively dropped support for older than 10.13 macOS versions (https://docs.travis-ci.com/user/reference/osx/#macos-version) since the ``opencv-python`` dependency chain is compiled / provided via Homebrew and Homebrew targets the OS version which it is running on. To my knowledge it cannot be forced to compile or use older macOS versions as a target.

I'll add some note about this to the readme.

**Comment by skvark** [comment]
There is a note in the readme now.
