### ISSUE TITLE
Why Qt libs are included in wheel

### ISSUE THREAD

**Issue by Czaki** [skvark/opencv-python#341]
### Expected behaviour

I expect to not bundle Qt libs in wheel but rather depends on ones provided by package (PyQt5, PySide2)

### Actual behaviour

in wheel (`.libs` for linux, `.dylibs` for macos) there are bundled Qt libs:

```
➜  cv2 ls .dylibs/Qt*
.dylibs/QtConcurrent   .dylibs/QtCore         .dylibs/QtDBus         .dylibs/QtGui          .dylibs/QtPrintSupport .dylibs/QtTest         .dylibs/QtWidgets
```

This produce such warning:
```
objc[18893]: Class QMacAutoReleasePoolTracker is implemented in both /Users/gbokota/.pyenv/versions/3.6.9/envs/partseg3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x1119e9060) and /Users/gbokota/.pyenv/versions/3.6.9/envs/partseg3.6/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x14538c700). One of the two will be used. Which one is undefined.
```

Which may break some applications
### Steps to reproduce
download and unpack wheel from pypi

**Comment by skvark** [comment]
Because Python's package management system doesn't provide a method to depend on other binary packages. The wheel packaging format is self-contained, ``auditwheel`` and ``delocate`` bundle external libs to the packages automatically. 

Making the package depend for example on PyQt5 might be doable if OpenCV could be able to find the compatible Qt libs from some other place provided by some other package. This should work reliably out-of-the-box without any import errors. I have no plans nor time to implement such feature, but I'm open to pull requests.

If you are already using those Qt wrappers for your GUI then it's probably easiest to use the ``opencv-python-headless`` package which do not bundle Qt or any other GUI libraries and build the UI with PyQt5 / PySide2 instead of using OpenCV's ``imshow`` etc. I'm not really sure what's the use case here, do you need also OpenCV's GUI methods for some reason?

**Comment by Czaki** [comment]
> If you are already using those Qt wrappers for your GUI then it's probably easiest to use the `opencv-python-headless` package which do not bundle Qt or any other GUI libraries and build the UI with PyQt5 / PySide2 instead of using OpenCV's `imshow` etc. I'm not really sure what's the use case here, do you need also OpenCV's GUI methods for some reason?

Ok thanks. It is not in my package but in package on which my project depends. 

There is some workaround using code which load it dynamically at runtime but I it may be not worth. 
see https://github.com/kiyo-masui/bitshuffle/issues/76#issuecomment-595661333
