### ISSUE TITLE
Binary descriptors for lines

### ISSUE THREAD

**Issue by manigoad** [skvark/opencv-python#352]
I have opencv-contrib-python==3.4.5.20 installed and I want to generate binary descriptors based on detected lines. According to the documentation - https://docs.opencv.org/3.4.5/dc/ddd/group__line__descriptor.html there is BinaryDescriptor but it seems it is not exposed in python.

### Only `cv2.line_descriptor_KeyLine` and `cv2.line_descriptor_LSDDetector` accessible

- mac OS 10.15.5
- architecture (e.g. x86)
- opencv-python 3.4.5.20

**Comment by skvark** [comment]
This repository does not contain OpenCV code, just the Python build toolchain. 

If some C++ method is missing from Python side, please request it at the actual OpenCV repository because the wrapper functions are automatically generated from the C++ headers (they must have certain wrapper macros defined). 

https://github.com/opencv/opencv/issues
