### ISSUE TITLE
`opencv-contrib-python-nonfree` is gone

### ISSUE THREAD

**Issue by davidraleigh** [skvark/opencv-python#354]
### Expected behaviour

We expected this pip package to continue to exist `opencv-contrib-python-nonfree`

### Actual behaviour

```
pip install opencv-contrib-python-nonfree
```

```
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python-nonfree
```

### Steps to reproduce

this no longer exists:
https://pypi.org/project/opencv-contrib-python-nonfree/

https://web.archive.org/web/20191217223511/https://pypi.org/project/opencv-contrib-python-nonfree/

**Comment by davidraleigh** [comment]
https://github.com/opencv/opencv/issues/17693

**Comment by skvark** [comment]
This repository never provided that distribution. That package was uploaded by someone else, see https://github.com/skvark/opencv-python/issues/348 for more info. I asked that person to remove my name from the PyPI (and any reference to this repo) because I do not want my name associated with packages which contain patented or potentially commercial algorithms.

Like the repository description says:

> Automated CI toolchain to produce precompiled opencv-python, opencv-python-headless, opencv-contrib-python and opencv-contrib-python-headless packages. 

Please check your dependencies with care before you start to use them.
