### ISSUE TITLE
ETA for OpenCV 4.4.0 support?

### ISSUE THREAD

**Issue by 2MinuteWarning** [skvark/opencv-python#364]
OpenCV 4.4.0 just released yesterday and has some amazing new features - including support for YOLOv4.

Is anyone here working on an update to this package to support?  ETA?

 - [X ] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
There is no ETA, would be good to get https://github.com/skvark/opencv-python/issues/362 fixed before any new releases are made.

**Comment by skvark** [comment]
Unfortunately those nonfree packages you are referring to were never provided by me or this repository in PyPI so I can't do much to help you with your problem. However, you can follow the manual build guide in the README https://github.com/skvark/opencv-python#manual-builds and use the official OpenCV docs if needed. Between step 2 and 3 go to the ``opencv`` (and ``opencv_contrib`` if you need it) submodule and checkout the latest tag or commit you wish to use (in your case probably ``4.4.0``).

I will release 4.4.0 wheels once the linked issue above is solved (it does not make any sense to push broken wheels to PyPI). I'm currently on vacation so that might take some time since I'm not planning to use all of my time doing open source development.

**Comment by skvark** [comment]
If all goes well, 4.4.0 wheels well be in PyPI during next week.

**Comment by 2MinuteWarning** [comment]
Awesome. 

Thank you for the update @skvark

**Comment by skvark** [comment]
3.4.11 release builds are now in progress. 4.4.0 will follow after them, packages should be available gradually in the next 24 hours.

**Comment by asi-alex-schultz** [comment]
Awesome, Thank you!

**Comment by skvark** [comment]
Released. Note that some Windows builds are still in progress.
