### ISSUE TITLE
installation is stuck at building wheel

### ISSUE THREAD

**Issue by Abhranta** [skvark/opencv-python#391]
### Expected behaviour

I expected to module to install very fast.

### Actual behaviour

Building wheel for opencv-python (PEP 517) takes forever to run.

### Steps to reproduce

- OS - ubuntu 18.04 LTS
- architecture - x86
- opencv-python version - 4.4.0.44

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by TheDudeThatCode** [comment]
@Abhranta ok so coincidently I too faced the similar issue just now 👇

![image](https://user-images.githubusercontent.com/41606999/93948205-682f4100-fd5b-11ea-87e6-b257b4c5f029.png)

- When I checked on [pypi.org](https://pypi.org/project/opencv-python/#history), I came to know that, people who all are installing openCV they are installing the latest version that is released just 3 hours back 👇

![image](https://user-images.githubusercontent.com/41606999/93948665-a416d600-fd5c-11ea-9b51-6a793c6a6069.png)



<br>

**TEMPORARY SOLUTION ✅**

So for now you can download the previous version (i.e [opencv-python 4.4.0.42](https://pypi.org/project/opencv-python/4.4.0.42/)) and it will work fine and your job gets done.

![image](https://user-images.githubusercontent.com/41606999/93949251-07edce80-fd5e-11ea-8bf8-49212af97e01.png)



Hope this helps 😊
Do drop a like if your issue gets solved by this.
Thank you 🙏

**Comment by siddharthcb** [comment]
hi @TheDudeThatCode ,
i tried installing the older version as you said but i am getting the same error still.
i am running on ubuntu 18.04, arm64.

python3.7 -m pip install opencv-python==4.4.0.42
Defaulting to user installation because normal site-packages is not writeable
Collecting opencv-python==4.4.0.42
  Using cached opencv-python-4.4.0.42.tar.gz (88.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.14.5 in ./.local/lib/python3.7/site-packages (from opencv-python==4.4.0.42) (1.19.2)
Building wheels for collected packages: opencv-python
  Building wheel for opencv-python (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 /home/farbot/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp2mtq9r3_
       cwd: /tmp/pip-install-88qrptpk/opencv-python
  Complete output (9 lines):
    File "/tmp/pip-build-env-xque07ot/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 560, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/tmp/pip-build-env-xque07ot/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/tmp/pip-build-env-xque07ot/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 82, in get_cmake_version
      "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)
  Traceback (most recent call last):
  
  Problem with the CMake installation, aborting build. CMake executable is cmake
  ----------------------------------------
  ERROR: Failed building wheel for opencv-python
Failed to build opencv-python
ERROR: Could not build wheels for opencv-python which use PEP 517 and cannot be installed directly

**Comment by skvark** [comment]
You can't install the packages because the builds were (and still are) in progress. Please pin your dependencies as @TheDudeThatCode wrote above. When builds are finished, you can safely upgrade (the new release contains only bug fixes and drops Python 3.5 support). The releases are usually ready when there are release notes at https://github.com/skvark/opencv-python/releases.

Build progress: https://ci.appveyor.com/project/skvark/opencv-python and https://travis-ci.com/github/skvark/opencv-python/builds

@siddharthcb This project does not support ARM platforms. Therefore your installation will always fail. Source build fails because `cmake` has issues with ARM platforms also.

**Comment by siddharthcb** [comment]
@skvark is it possible to build from source for arm64?
what approach do you recommend for arm64?

**Comment by skvark** [comment]
If you manage to get the `cmake` dependency working (in `pyproject.toml`) then this project should build fine on arm64. Please see https://github.com/skvark/opencv-python/issues/366 for more info. Cmake is provided via this project: https://github.com/scikit-build/cmake-python-distributions

**Comment by Patrickctyyx** [comment]
Met the same problem, solving by upgrade pip before install opencv, `pip install --upgrade pip`

**Comment by ArturoHurtado7** [comment]
> Met the same problem, solving by upgrade pip before install opencv, `pip install --upgrade pip`

thanks bro, this worked for me

**Comment by yoyojacky** [comment]
just:
```
pip install opencv-python==4.5.3.56 
```
it works fine for me.

**Comment by makarpeter98** [comment]
Thanks man!
I spend my last 4-5 days and some nights to find the solution. 
I need the OCV to my thesis.

> just:
> 
> ```
> pip install opencv-python==4.5.3.56 
> ```
> 
> it works fine for me.

**Comment by jiachengc** [comment]
> just:
> 
> ```
> pip install opencv-python==4.5.3.56 
> ```
> 
> it works fine for me.

You save my life

**Comment by VivianChan98** [comment]
> just:
> 
> ```
> pip install opencv-python==4.5.3.56 
> ```
> 
> it works fine for me.

Weekend saved. Thanks

**Comment by ProfessorShroom** [comment]
I'm getting this with 4.8.1.78.
Building wheel for opencv-python (pyproject.toml) ... has been going for over an hour

**Comment by Gnonymous** [comment]
> just:
> 
> ```
> pip install opencv-python==4.5.3.56 
> ```
> 
> it works fine for me.

thank you! it also works for me 
As blew is what l have done:
1. `conda create -n name python=3.8` someone said python3.8 is necessary
2. `pip3 install opencv-python==4.5.3.56`

**Comment by ProfessorShroom** [comment]
> > just:
> > ```
> > pip install opencv-python==4.5.3.56 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it works fine for me.
> 
> thank you! it also works for me As blew is what l have done:
> 
>     1. `conda create -n name python=3.8` someone said python3.8 is necessary
> 
>     2. `pip3 install opencv-python==4.5.3.56`

4.5.3.56 does install very quickly however I get this error when running my script
Traceback (most recent call last):
   File "/home/obd/.local/lib/python3.9/site-packages/numpy/__init__.py", line 135, in <module>
     raise ImportError(msg) from e
 ImportError: Error importing numpy: you should not try to import numpy from
         its source directory; please exit the numpy source tree, and relaunch
         your python interpreter from there.
 Traceback (most recent call last):
   File "/home/obd/DRDS/main.py", line 18, in <module>
     import cv2
   File "/home/obd/.local/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
     from .cv2 import *
 ImportError: numpy.core.multiarray failed to import

**Comment by Aroopjosy** [comment]
try this version ##pip install opencv-python==4.5.3.5
in my case it works

**Comment by Fernadoo** [comment]
> just:
> 
> ```
> pip install opencv-python==4.5.3.56 
> ```
> 
> it works fine for me.

Thank you, Mr. Save-My-Day, it only took a few seconds to build itself.

**Comment by hisan-ideamaker** [comment]
> Met the same problem, solving by upgrade pip before install opencv, `pip install --upgrade pip`

The best solution out there. Worked for me. Should be on the top !!!
