### ISSUE TITLE
Installation of headless version crashes with "ModuleNotFoundError: No module named 'skbuild'"

### ISSUE THREAD

**Issue by codinghedgehog-python** [skvark/opencv-python#405]
### Expected behaviour

Install the library into container like a breeze.

### Actual behaviour

Errors out with "ModuleNotFoundError: No module named 'skbuild'" even after upgrading pip to latest available version.

### Steps to reproduce

- Ubuntu 20.04
- pip 20.2.4
- Docker version 19.03.13, build 4484c46d9d
- docker-compose version 1.25.0
- Python 3.7.2-alpine
- opencv-python-headless v. 4.4.0.44

I've seen topics on the Internet where upgrading pip usually solved the problem. Not in my case though.

I've tried to install `opencv-contrib-python-headless` instead but got: `Could not find a version that satisfies the requirement`. Installing the library for Docker has become quite a mission.

**Comment by skvark** [comment]
Alpine Linux is not supported by the `manylinux` standard. Alpine is based on `musl` C library and `manylinux` requires a GNU/Linux system with `glibc`. Hacky workarounds can be found from here: https://github.com/pypa/pip/issues/3969

You did not post the full error output, but the I believe the error comes from `cmake` and not from `opencv-python`. 

`opencv-contrib-python-headless` throws that error because it seems that I have hit the PyPI file size limit so some of the source distributions haven't been uploaded properly to PyPI.

**Comment by codinghedgehog-python** [comment]
Bare bones Alpine version was the catch here yeah. I switched to slim and all was OK. Closing this with thanks.
