### ISSUE TITLE
opencv-python-headless installation bug

### ISSUE THREAD

**Issue by lgvaz** [skvark/opencv-python#411]
### Bug

Trying to install the newest version of `opencv-python-headless` from pypi (4.4.0.46) gets stuck at:
```
Building wheel for opencv-python-headless (PEP 517) ...
```

### Steps to reproduce

- Create a fresh environment
- run `pip install opencv-python-headless` 

Or simply, check [this](https://colab.research.google.com/drive/1fpYxhONOPeJv19uzIYKvSbG6QUEx74iI?usp=sharing) colab notebook.

### Full stack trace
```python
Collecting opencv-python-headless
  Downloading https://files.pythonhosted.org/packages/07/e3/db18943862e08f444718952ef8cf80ea5b847fa20894227a22f3a5478575/opencv-python-headless-4.4.0.46.tar.gz (88.9MB)
     |████████████████████████████████| 88.9MB 108kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from opencv-python-headless) (1.18.5)
Building wheels for collected packages: opencv-python-headless
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by overclock98** [comment]
install !pip install opencv-python-headless==4.2.0.34

**Comment by skvark** [comment]
It's not stuck, just building from source since there are no pre-built wheels published yet. OpenCV is a very heavy C++ project and it takes 10 minutes even on 8-core CPUs to build it - on a Raspberry Pi it takes over 2 hours. 

I hit the PyPI 20 GB project size limit during last release so it's going to take some time to clean up old releases and upload new the pre-built wheels. Please pin your dependencies, opencv-python-headless==4.4.0.44 is the same release as 4.4.0.46 which just adds Python 3.9 wheels.

**Comment by skvark** [comment]
Most of the wheels are now up. Windows builds still take some time to finish: https://ci.appveyor.com/project/skvark/opencv-python/history
