### ISSUE TITLE
VideoCapture() attribute works on laptop but throws "(-2:Unspecified error)" on Android

### ISSUE THREAD

**Issue by codinghedgehog-python** [skvark/opencv-python#413]
I'm testing app which uses opencv-python 4.4 on Android and in the moment when the app supposed to launch camera the camera won't launch and in logs I get:

`cv2.error: OpenCV(4.0.1) /home/mark/frontend_android/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/opencv/armeabi-v7a__ndk_target_21/opencv/modules/highgui/src/window.cpp:610: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'`

I installed `libgtk2.0-dev` and `pkg-config` was already present.

pip packages I'm using:

`opencv-python==4.4`
`opencv-contrib-python==4.4`

I've found the below mentioned on the web:
  

>     MacOS and Linux wheels have currently some limitations:
> 
>     video related functionality is not supported (not compiled with FFmpeg)
>     for example
>     cv2.imshow()
>     will not work (not compiled with GTK+ 2.x or Carbon support)

I'm not using `imshow()` attribute but I do use `VideoCapture(0)`.

Versions used:

opencv-python 4.4
opencv-contrib-python 4.4
python-for-android 2020.6.2
python 3.8.5
Ubuntu 20.04

**Comment by skvark** [comment]
This repository does not support ARM platforms. Your issue is not related to this repository, you are mixing here your host platform and target platform. There are no pre-built wheels for Android, and you must be using `imshow` if you get that error. If you built the package from sources, then it's your job to configure the build parameters via CMake.

```
pip packages I'm using:

opencv-python==4.4
opencv-contrib-python==4.4
```

This is wrong. You can't use both packages at the same time. Please read the installation guide in the README and please understand that those packages are installed to your Ubuntu systems, not to your Android environment. This is clearly indicated by the error message which has completely different OpenCV version: cv2.error: OpenCV(**4.0.1**).
