### ISSUE TITLE
Python package for opencv 4.5

### ISSUE THREAD

**Issue by moneer88** [skvark/opencv-python#415]
Dear Skvark 

is there any timelines for building a new package for opencv 4.5?

Regards

**Comment by skvark** [comment]
All new releases are currently blocked by this: https://github.com/pypa/pypi-support/issues/712

4.5 wheels will be released when PyPI support raises the project size limit.

**Comment by ishirav** [comment]
Hi, any update on this?
Thank you for all your hard work!

**Comment by skvark** [comment]
There are issues with macOS builds (cache stage & with homebrew in general) and Travis. 

The whole Travis side of the CI toolchain needs to be refactored to some other build system since Travis does not provide a free plan anymore. For more information, check out this blog post: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works 

I have some "trial" credits remaining in Travis but I don't know if I'm able the fit any new releases inside that quota. I have absolutely zero interest in begging for some open-source quota from Travis monthly or more often. In any case, a large amount of refactoring is needed. I don't know if I have the time or energy to make the changes during this year.

**Comment by Pro100rus32** [comment]
Hello!

Can I know if the update is coming soon?

**Comment by skvark** [comment]
4.5.1 maybe this week if there are enough Travis credits left. The latest 3.4.x branch probably not possible before we have migrated away from Travis.

**Comment by skvark** [comment]
4.5.1 builds are running. Please note that Qt support was dropped in macOS wheels. If the native Cocoa GUI support is not enough, consider contributing: 

- https://github.com/skvark/opencv-python/issues/376
- https://github.com/skvark/opencv-python/issues/423
