### ISSUE TITLE
I am getting this issue when installing opencv-3.4.3.18

### ISSUE THREAD

**Issue by saad-sifar** [skvark/opencv-python#438]
### Expected behaviour

I wanted to install this specific version of open cv

### Actual behaviour

It didn't work, the terminal says
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.3.18
ERROR: No matching distribution found for opencv-python==3.4.3.18

### Steps to reproduce

- python -m pip install opencv-python==3.4.3.18 numpy==1.14.5 onnx==1.6.0 onnxruntime==1.0.0
- Windows
- architecture (e.g. x86)
- opencv-python==3.4.3.18

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
What's the version of your Python? 

3.4.3.18 (https://pypi.org/project/opencv-python/3.4.3.18/#files) is 2,5 years old release. 

It supports only 2.7, 3.5, 3.6 and 3.7. Python **3.8** and **3.9** were not supported at that time because they didn't exists back then -- please update your `opencv-python` version.
