### ISSUE TITLE
Non-free opencv_contrib modules are not available

### ISSUE THREAD

**Issue by espdev** [skvark/opencv-python#51]
I try to use opencv-contrib-python wheel package from PyPI

### Expected behaviour

```python
import cv2
out_img = cv2.xphoto.bm3dDenoising(inp_img)
# No any errors
```

### Actual behaviour

I get the following error
```
cv2.error: C:\projects\opencv-python\opencv_contrib\modules\xphoto\src\bm3d_image_denoising.cpp:341: error: (-213) This algorithm is patented and is excluded in this configuration;Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function cv::xphoto::bm3dDenoising
```

**Comment by techdragon** [comment]
@espdev unfortunately the pre-built wheel can't include this. 

This is similar to why work on #49 and #50 has to build LGPL versions of FFmpeg. Some things are just not safe for developers like us to distribute without the risks of legal repercussions. Pre-built Wheels will not be able to include these components. 

Future work on an sdist might be able to mitigate this by performing the compilation on end users machine and thus not distributing potentially infringing software. But the focus of work here has been on building Wheels that enable users to install OpenCV without the need to spend the time compiling OpenCV. 

@skvark Might have more to say. But I feel like I had a good answer for you since I'm digging around on the FFmpeg issues which have similar legal related constraints. My apologies if I've overstepped here in what is effectively answering for you ( @skvark ) as the project owner.

**Comment by skvark** [comment]
OpenCV cmake recipe has enable-nonfree flag but it's currently off. As @techdragon explained above, I'm not sure if we can distribute the modules protected by that flag. This would require lawyer advice.

Note: despite the flag being off there _might be_ some other modules included in opencv-contrib-python which belong to the same "non-free" category. If that's the case it's because OpenCV developers haven't protected them by that macro.

**Comment by espdev** [comment]
@techdragon @skvark Thank you for your replies! You right.

I think I could build wheel package for myself with needed opencv cmake-flag but I do not know how to build this project correctly.

**Comment by skvark** [comment]
Currently you can build custom versions only by forking the project and changing builds flags. On Appveyor the build artifacts can be downloaded after the build from the Appveyor service.

At some point it will also possible to build the package locally, see this issue: https://github.com/skvark/opencv-python/issues/43
