### ISSUE TITLE
JPEG decoding and encoding is significant slower than from Ubuntu package

### ISSUE THREAD

**Issue by homm** [skvark/opencv-python#52]
First of all thanks for your work!

OpenCV version in Ubuntu 16.04 is still 2.4.9.1, so most users have to install OpenCV from this wheels.

Surprisingly, these wheels have much lower JPEG decoding and encoding speed than shipped with Ubuntu.
 
```
Cv2 load 2560×1600 RGB image
    Jpeg load           0.05430 s    75.43 Mpx/s
    Jpeg save           0.10867 s    37.69 Mpx/s
Cv2 load 2560×1600 RGB image
    Jpeg load           0.03277 s   124.99 Mpx/s
    Jpeg save           0.03084 s   132.82 Mpx/s
```

Here is `perf report` for both cases:

<img width="580" alt="screen shot 2017-10-16 at 1 39 58" src="https://user-images.githubusercontent.com/128982/31590069-0bcbff20-b213-11e7-991f-8cdf839f477b.png">
<img width="708" alt="screen shot 2017-10-16 at 1 17 12" src="https://user-images.githubusercontent.com/128982/31590070-0ea56fc4-b213-11e7-9745-58b5d58b5505.png">

It's clear that these wheels don't use system-provided libjpeg library (which is libjpeg-turbo for some systems). Instead, they are decoding and encoding using some build-in libjpeg library which is much slower.

I see two solutions: use libjpeg-turbo for wheels or use system libraries.

**Comment by homm** [comment]
I've tried to build recent version of  OpenCV from sources, it also uses system codecs and run fast

**Comment by skvark** [comment]
Yes, due to the nature of the wheel packaging format requirements (restricted subset of the Linux kernel and core userspace ABI) almost all of the needed libraries are embedded into the wheels. However, libjpeg's case is a bit different because the it's most likely included in the static OpenCV binary.

I'm pretty sure I can change the library to libjpeg-turbo, but it requires a lot of manual tinkering on the CentOS 5 Docker containers (like all the other open Linux related issues which are currently open).

**Comment by skvark** [comment]
Next release will ship with libjpeg-turbo 1.5.3.
