### ISSUE TITLE
Problem caused by the change from libjpeg to libjpeg-turbo

### ISSUE THREAD

**Issue by Marco-LIU** [skvark/opencv-python#65]
### Expected behaviour

cv2.imread in different versions should return same values for the same JPG file.

### Actual behaviour

![001](https://user-images.githubusercontent.com/1195343/35255237-0e0218ce-0029-11e8-9a18-e54b6a3dfcea.jpg)
For this image(w=153, h=209), pixel[0, 207] will get different value between 3.3 and 3.4
![screenshot from 2018-01-19 18-41-01](https://user-images.githubusercontent.com/1195343/35255364-a31bf768-0029-11e8-97ee-bd720f44280a.png)
In 3.3, pixel[0, 207]  = [115, 52, 226]
![screenshot from 2018-01-19 18-42-01](https://user-images.githubusercontent.com/1195343/35255368-a6fb0a18-0029-11e8-8467-3717fa11b9af.png)
In 3.4, pixel[0, 207]  = [111, 52, 223]

### Steps to reproduce

- example code
  `import cv2`
  `print(cv2.__version__)`
  `img = cv2.imread('001.jpg')`
  `print(img[0, 207])`
- operating system
  linux
- architecture (e.g. x86)
  x64
- opencv-python version
  3.4

I have tested the libjpeg and libjpeg-turbo, and this difference is caused by these two libs. (Test code in https://github.com/Marco-LIU/libjpeg-test)

Though the libjpeg-turbo has better performance than libjpeg, this difference will make a TRAP, and cause some machine learning models give DIFFERENT results for same input file. We've trained a model in v3.3, but got a wrong test result in v3.4 for that beauty pic.

**Comment by skvark** [comment]
Hmm, I thought that I already wrote a reply here but apparently I didn't... 

Anyhow, I can confirm that there seems to be differences between these libraries. Most likely the issue is related to the optimizations which have been done in libjpeg-turbo. I have no way of knowing what might cause these differences but I presume that different decoding algorithms are used under the hood. In addition, the usage SIMD extensions might cause some inaccuracies to the results. Due to the nature of the JPEG's lossy format there's no way to "fix" this issue.

I'll be changing also macOS and Windows jpeg libs to libjpeg-turbo at some point. You can always compile OpenCV by yourself if you need extremely stable environment. I hope you understand that I cannot guarantee that these builds remain consistent across releases.
