### ISSUE TITLE
Error on cv2.circle with "same" input arrays

### ISSUE THREAD

**Issue by mmeendez8** [skvark/opencv-python#741]
### Expected behaviour

Opencv circle works with numpy arrays with same shape and dtype.

### Actual behaviour

Depending on array creation method (probably related with numpy internals) opencv.circle() returns an error

### Steps to reproduce

- example code
```python
import cv2
import numpy as np

a = np.zeros((720, 1280, 2), dtype=np.uint8)
b = np.zeros((720, 1280), dtype=np.uint8)

cv2.circle(b, (100,100),3,1,-1)   # works
cv2.circle(a[..., 0], (100,100),3,1,-1)  # does not work
```

- operating system
Ubuntu 20.04.3 LTS

- architecture (e.g. x86)
x86_64

- opencv-python version
opencv-python                     4.6.0.66

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by mmeendez8** [comment]
Just found that this can be solved by passing a contiguous array as:

```python
cv2.circle(np.ascontiguousarray(a[..., 0]), (100,100),3,1,-1)
```

Nevertheless this is exposing numpy internals to users... not sure if these cases should be controlled by opencv

**Comment by asmorkalov** [comment]
OpenCV uses numpy arrays instead of cv::Mat in Python, but does not support array-like objects and iterators as they cannot be easily passed to C++ function as a parameter. So it's expected behavior. You can check it by printing of `a[..., 0]` object type.

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/pull/22822

**Comment by asmorkalov** [comment]
Ok. I tested the PR and debugged the issue. OpenCV `cv::Mat` and `cv::Umat` support per-row step, but not per-element step. It means that elements in a row should be compact without holes. `a[..., 0]` creates array with per-element step. This memory layout cannnot be converted to `cv::Mat` automatically and the only solution is data copy. It could be achieved with `np.ascontiguousarray(a[..., 0])` or cv.split call: https://docs.opencv.org/4.x/d2/de8/group__core__array.html#ga0547c7fed86152d7e9d0096029c8518a. The mentioned PR is not relevant to the issue. So it could not be fixed in OpenCV Python bindings. I close the issue.
