### ISSUE TITLE
Clarification about FFmpeg version

### ISSUE THREAD

**Issue by marcokuchla** [skvark/opencv-python#85]
Which version of ffmpeg does the package use? 
I've tried to find anything about FFmpeg's version that is being used by this project, but unfortunately I haven't found any clues.
My motivation about this question is that the new major release of FFmpeg (4.0) includes support for AV1 codec through libaom, and I intend to test this new codec.

**Comment by skvark** [comment]
On GNU/Linux the version is the latest  snapshot which was available when the manylinux images were built: 

--     FFMPEG:                      YES
--       avcodec:                   YES (ver 58.6.103)
--       avformat:                  YES (ver 58.3.100)
--       avutil:                    YES (ver 56.5.100)
--       swscale:                   YES (ver 5.0.101)
--       avresample:                NO

Linux wheels will get the latest available FFmpeg version soon. I'm currently trying to rebuild the ``manylinux`` images locally (new ``opencv-python`` releases are blocked because of some issues with the current images, e.g. too old TLS version) but it's pretty complicated process due to very old Cent OS 5 images.

On macOS the version depends on what comes from Homebrew:

--     FFMPEG:                      YES
--       avcodec:                   YES (ver 57.107.100)
--       avformat:                  YES (ver 57.83.100)
--       avutil:                    YES (ver 55.78.100)
--       swscale:                   YES (ver 4.8.100)
--       avresample:                YES (ver 3.7.0)

The build information can be viewed with ``cv2.getBuildInformation()``.

Version information about FFmpeg is here: https://www.ffmpeg.org/download.html
