### ISSUE TITLE
Bug in open jp2 image

### ISSUE THREAD

**Issue by wukongtea** [skvark/opencv-python#92]
Can't open a .jp2 image, but i can open it  in the matlab or other software.

example code
import cv2
img = cv2.imread("F:\Test\others.jp2")
img.shape

AttributeError                            Traceback (most recent call last)
<ipython-input-54-32fc80199a64> in <module>()
      2 import cv2
      3 img = cv2.imread("F:\Test\others.jp2")
----> 4 img.shape

AttributeError: 'NoneType' object has no attribute 'shape'

The data is here 

[image.zip](https://github.com/skvark/opencv-python/files/1991774/image.zip)

**Comment by skvark** [comment]
It seems that the decoder in OpenCV doesn't support the format of that file:

```
>>> image = cv2.imread("C:\\Users\\username\\Downloads\\image\\others.jp2")
OpenCV(3.4.1) Error: Assertion failed (sgnd == 0 && "not supported") in cv::Jpeg2KDecoder::readHeader, file C:\projects\opencv-python\opencv\modules\imgcodecs\src\grfmt_jpeg2000.cpp, line 147
imread_('C:\Users\username\Downloads\image\others.jp2'): can't read header: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\imgcodecs\src\grfmt_jpeg2000.cpp:147: error: (-215) sgnd == 0 && "not supported" in function cv::Jpeg2KDecoder::readHeader
```
However, the decoder works fine when try this image: https://github.com/bitsgalore/jp2kMagic/blob/master/sampleImages/balloon.jp2
```
>>> img = cv2.imread("C:\\Users\\username\\Downloads\\balloon.jp2")
>>> img.shape
(3701, 2717, 3)
```
There are known issues with ``libjasper`` which is used in OpenCV for jp2 images (https://github.com/opencv/opencv/issues/5849). I can't fix these issues in this repository since this is just a very simple wrapper package. You should open an issue to the OpenCV repository.
