### ISSUE TITLE
vscode Syntax error

### ISSUE THREAD

**Issue by isdqwq** [skvark/opencv-python#95]
python 3.6.5 x64 
os: win10 x64
```
pip3 install opencv-python
pip3 install opencv-contrib-python
```
`visual studio code` install  python,python for vscode
and import cv2 ,and call cv2 function,get below error meesage, but the code work ok. just pylint show the error message

**how to fix ,thanks**
![image](https://user-images.githubusercontent.com/16586516/40355712-baa97b94-5de9-11e8-9db0-958c796931db.png)

**Comment by waveform80** [comment]
You probably need to whitelist the package - see [this SO question](https://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members) for more info

**Comment by skvark** [comment]
See the link that was posted by @waveform80 above. And please do not install many different packages in the same environment. There's no "plugin architecture". You should install only `opencv-python` or `opencv-contrib-python`. If you install both packages next to each other the environment will get mixed up because there are multiple different packages using the same namespace which in turn might cause similar problems.

**Comment by isdqwq** [comment]
@skvark  @waveform80  thanks for your replay.
 It's work ok  after i remove opencv-contrib-python and only install opencv-python ,thanks very much
